services:
  postgres:
    image: postgres:15
    container_name: postgres_identity
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: StrongPassword123!
      POSTGRES_DB: IdentityDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - identity_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_identity
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - identity_network

volumes:
  pgdata:

networks:
  identity_network: